import type { Metadata } from "next";
import {  Raleway } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Raleway({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FOSO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className}  antialiased`}
      >
        <div className="h-screen overflow-y-auto px-2">
          <Header/>
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
